### PR TITLE
Enable feature to fix unstabilized `#[bench]`

### PR DESCRIPTION
**Pull request by vorot93**
rust-lang/rust#62507

### CODE REVIEW

**Comment by Nemo157** [comment]
This will cause this crate to become nightly only, #25 is a better fix that will still allow building on stable 1.38+.

**Comment by vorot93** [comment]
Inspired by the fix in cargo, missed the one you linked. Feel free to close if that one gets merged.

**Comment by vorot93** [comment]
ping @alexcrichton

**Comment by miller-time** [comment]
yeah if https://github.com/rust-lang/cargo/pull/7198 was the inspiration, that's just tests...

**Comment by alexcrichton** [comment]
Sorry, but I am no longer maintaining this crate.

**Comment by vorot93** [comment]
But who is? Perhaps it should be transferred to rustasync since it is used by tide?

**Comment by yoshuawuyts** [comment]
> Perhaps it should be transferred to rustasync since it is used by tide?

We'd be happy to help share the maintenance burden if desired!

**Comment by Nemo157** [comment]
@vorot93 thanks for this, I've merged #25 instead and published 0.1.13 now which should work on current nightlies.

**Pull request closed without merging**
