### PR TITLE
Clippy and format fixes

### PR DESCRIPTION
**Pull request by k-nasa**
## Description

Clippy and format fixes.

## How Has This Been Tested?

Run test code.

## Types of changes

- [x] Refactor

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [CONTRIBUTING](https://github.com/rust-net-web/tide/blob/master/.github/CONTRIBUTING.md) document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by gameldar** [comment]
Nice - I had been fixing these as well.

If this is running in CI with the same clippy rules as Tide then it is still going to fail (once the feature flag is merged) with the following error:
```
error: explicit lifetimes given in parameter types where they could be elided (or replaced with `'_` if needed by type declaration)
  --> src\lib.rs:90:5
   |
90 | /     pub fn iter<'a>(&'a self) -> Iter<'a> {
91 | |         Iter(self.map.iter())
92 | |     }
   | |_____^
   |
   = note: `-D clippy::needless-lifetimes` implied by `-D warnings`
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_lifetimes

error: aborting due to previous error
```

Looks like it still needs that addressed with the following:
```patch
@@ -85,11 +85,11 @@ impl Params {
 
     pub fn find(&self, key: &str) -> Option<&str> {
         self.map.get(key).map(|s| &s[..])
     }
 
-    pub fn iter<'a>(&'a self) -> Iter<'a> {
+    pub fn iter(& self) -> Iter<> {
         Iter(self.map.iter())
     }
 }
 
 impl<'a> Index<&'a str> for Params {
```

**Comment by k-nasa** [comment]
thx gameldar. I fixed it by 418d003

**Comment by gameldar** [comment]
Looks good to me now - I'd merged it if I could :)

**Comment by Nemo157** [comment]
I think we should release a new patch version and merge this for the next minor version bump, I think the `'_` lifetime will require a newer compiler than what the current release requires (although there's no published minimum compiler version currently).

I'm planning on doing a release in a few hours to get the fix for compiling on current nightly out, then I could merge this.

**Comment by Nemo157** [comment]
@k-nasa so that we can try and get this crate relicensed, can you make a statement like:

> I license this contribution under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option

(I'll try and add something to the repo for future PRs soon, but want to wait and see if there's any movement on #19 first).

**Comment by k-nasa** [comment]
@Nemo157 I added a lot.  Is this all right?
I am not good at english
I may have misunderstood

**Comment by gameldar** [comment]
I think Nemo meant to add that text as a comment on Issue #19 saying that you are fine with changing the license to the dual license since you are committing under the old license.

But what you have done does need doing - so we can still use that - we just need to still get approval for the change from Alex and Wycats

**Comment by Nemo157** [comment]
Yeah, that's what I meant, but this works fine as well. I've merged the original clippy and format fixes in, and split the rest of the changes off to #32.

**Pull request closed without merging**
